on:
  push:

jobs:

  test-go:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-go@v2'
        with:
          go-version: '^1.15'
      - run: |
          go test ./...
          go version

  testing.templated.build.Dockerfile:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: 'actions/checkout@v2'
      - run: docker build -f testing.templated.build.Dockerfile .